In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [3]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [4]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [5]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([2, 2, 1, 2, 2, 1, 2, 2, 1])

In [6]:
#expand dimension
arr = np.array([1, 2, 3, 4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [10]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means column wise(y axis)

array([[1, 2, 3, 4]])

In [11]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr, axis=1).ndim

2

In [13]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr, axis = 0).ndim

3

In [16]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr, axis = 0).ndim

3

In [18]:
a = np.array([[1], [2], [3]])

In [19]:
a

array([[1],
       [2],
       [3]])

In [20]:
a.ndim

2

In [21]:
#squeezing the dimension by 1 dimension
np.squeeze(a)#Remove axes of length one from `a`

array([1, 2, 3])

In [22]:
a

array([[1],
       [2],
       [3]])

In [23]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [24]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [25]:
np.repeat(arr1, 2)

array([2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1])

In [26]:
np.repeat(arr1, 2, axis=0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [28]:
np.repeat(arr2, 3, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [29]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 1, 1, 1]])

In [30]:
a

array([[1],
       [2],
       [3]])

In [31]:
np.roll(a, -1) #shift place

array([[2],
       [3],
       [1]])

In [32]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [35]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [36]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [39]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [41]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [42]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [43]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 2],
       [4, 4, 2]])

In [44]:
arr1-arr2

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [45]:
arr1 * arr2

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [46]:
arr1 > arr2

array([[False,  True, False],
       [ True,  True, False],
       [False, False, False]])

In [47]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [48]:
~arr1

array([[-3, -3, -2],
       [-3, -3, -2],
       [-3, -3, -2]])

In [49]:
#operations on numpy string array

d = np.array(["pw", "skills"])

In [50]:
d

array(['pw', 'skills'], dtype='<U6')

In [51]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [52]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [53]:
#mathematical function

In [54]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [55]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098]])

In [56]:
np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231]])

In [57]:
np.tan(arr1)

array([[-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772]])

In [58]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [59]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [60]:
np.power(arr1, 3)

array([[8, 8, 1],
       [8, 8, 1],
       [8, 8, 1]])

In [62]:
np.max(arr1)

2

In [63]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [64]:
np.mean(arr1)

1.6666666666666667

In [65]:
np.min(arr1)

1

In [66]:
np.std(arr1)

0.4714045207910317

In [67]:
np.var(arr1)

0.2222222222222222

In [68]:
arr1-arr2

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [69]:
np.subtract(arr1, arr2)

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [70]:
arr1*arr2

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [72]:
np.multiply(arr1, arr2)

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [73]:
np.mod(arr1, arr2) #return element wise remainder

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [75]:
#sorting and searching in numpy array
e = np.array([5, 6, 1, 2])

In [76]:
e

array([5, 6, 1, 2])

In [77]:
np.sort(e) #Return a sorted copy of an array.

array([1, 2, 5, 6])

In [78]:
f = np.array([5, 199, 200, 6, 7, 8])
f

array([  5, 199, 200,   6,   7,   8])

In [79]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [80]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

6

In [81]:
f = np.array([5, 199, 200,0, 0, 0, 0, 6, 7, 8])
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [83]:
np.count_nonzero(f)

6

In [85]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [86]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 7, 8, 9]),)

In [87]:
np.extract(f>0, f) #same as above condition

array([  5, 199, 200,   6,   7,   8])

In [88]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [89]:
f.byteswap() #Swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
                          0,   432345564227567616,   504403158265495552,
         576460752303423488])

In [90]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [92]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
#numpy linear algebra(optonal)

In [94]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [95]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [96]:
arr1@arr2

array([[8, 6, 7],
       [8, 6, 7],
       [8, 6, 7]])

In [97]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [98]:
np.linalg.det(arr1)

0.0

In [99]:
np.linalg.det(arr2)

-1.0

In [101]:
#in matrix you can not devide by another matrix, you have inverse
np.linalg.inv(arr2)

array([[ 1., -3.,  1.],
       [-1.,  2.,  0.],
       [ 0.,  2., -1.]])

In [102]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [103]:
b = np.array([16, 8, 0])

In [104]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])